### ISSUE TITLE
当tableView的frame不是self.view.bounds时,会出现占位图位置错误

### ISSUE THREAD

**Issue by Antduo** [XiaoWuTongZhi/WyhShowEmpty#1]
如果将tableView的frame设置成CGRectMake(0, 300, ScreenSize.width, ScreenSize.height-300),表的的位置尽量靠下,就会出现占位图的位置仍在屏幕中间的bug

**Comment by yuehengwu** [comment]
非常感谢您的问题 发现确实存在这个问题
已经针对您的问题处理解决了
请尝试下载最新版
@WB326
